// AUTO-GENERATED from weapons.xlsx
export const S3_DATA = {
  "__special__": [
    { roll: "1", name: "Enchanted Enhancements*" },
    { roll: "2", name: "Weapon Enhancements*" },
    { roll: "3", name: "Accelerator" },
  ],
  "Arrow": [
    { roll: "4", name: "Abaris'" },
    { roll: "5", name: "Acid" },
    { roll: "6", name: "of Aggravation" },
    { roll: "7", name: "Antimagic" },
    { roll: "8", name: "Apollo's" },
    { roll: "9", name: "of Attraction" },
    { roll: "10", name: "of Biting" },
    { roll: "11", name: "Black of Iuz" },
    { roll: "12", name: "of Blinding" },
    { roll: "13", name: "of Blinking" },
    { roll: "14", name: "Bolt of Lightning" },
    { roll: "15", name: "of Bow-Breaking" },
    { roll: "16", name: "of Burning" },
    { roll: "017-018", name: "of Charming" },
    { roll: "19", name: "of Charming II" },
    { roll: "20", name: "of Clairaudience" },
    { roll: "21", name: "of Clairvoyance" },
    { roll: "22", name: "of Climbing" },
    { roll: "23", name: "of Connection" },
    { roll: "24", name: "of Curing" },
    { roll: "25", name: "of Darkness" },
    { roll: "26", name: "of Detonation" },
    { roll: "27", name: "of Direction" },
    { roll: "28", name: "of Disarming" },
    { roll: "29", name: "of Disintegration" },
    { roll: "30", name: "of Dispelling" },
    { roll: "31", name: "of Distance" },
    { roll: "32", name: "of Draconian Slaying" },
    { roll: "33", name: "Elven" },
    { roll: "34", name: "of Enchantment" },
    { roll: "035-036", name: "of Explosions" },
    { roll: "37", name: "of Extended Range" },
    { roll: "38", name: "Faerie Fire" },
    { roll: "39", name: "of Fire" },
    { roll: "40", name: "Fire Seed" },
    { roll: "41", name: "Fire Trap" },
    { roll: "42", name: "Flaming" },
    { roll: "43", name: "of Flying" },
    { roll: "44", name: "of Force" },
    { roll: "45", name: "of Harm" },
    { roll: "46", name: "of Holding" },
    { roll: "47", name: "of Holding II" },
    { roll: "48", name: "of Ice" },
    { roll: "49", name: "of Illumination" },
    { roll: "50", name: "Illusory Missile" },
    { roll: "51", name: "of Justice" },
    { roll: "052-053", name: "of Law" },
    { roll: "54", name: "of Light" },
    { roll: "55", name: "of Lighting" },
    { roll: "56", name: "of Lightning" },
    { roll: "57", name: "Lycanthrope Slayer" },
    { roll: "58", name: "Maglubiyet's Wounding" },
    { roll: "59", name: "of Misdirection" },
    { roll: "60", name: "Missile Weapon of Accuracy" },
    { roll: "61", name: "Missile Weapon of Distance*" },
    { roll: "62", name: "of Multiplicity" },
    { roll: "63", name: "Nilbog" },
    { roll: "64", name: "Oberon's of Subduing" },
    { roll: "65", name: "Oberon's of Slaying" },
    { roll: "66", name: "of Paralyzation" },
    { roll: "67", name: "of Penetrating" },
    { roll: "68", name: "of Penetration" },
    { roll: "69", name: "of Perseverance" },
    { roll: "070-071", name: "of Piercing" },
    { roll: "72", name: "of Polymorphing" },
    { roll: "73", name: "of Pursuit" },
    { roll: "74", name: "Quarrel of Biting (Acid)" },
    { roll: "75", name: "Quarrel of Biting (Normal)" },
    { roll: "76", name: "Quarrel of Biting (Poison)" },
    { roll: "77", name: "Red" },
    { roll: "78", name: "of Refilling" },
    { roll: "79", name: "of Returning" },
    { roll: "80", name: "of Rock Piercing" },
    { roll: "81", name: "of Roping" },
    { roll: "82", name: "of Scent Detection" },
    { roll: "83", name: "of Screaming" },
    { roll: "84", name: "of Screaming II" },
    { roll: "85", name: "of Seeking" },
    { roll: "86", name: "of Seeking II" },
    { roll: "87", name: "of Set" },
    { roll: "088-089", name: "of Signaling" },
    { roll: "90", name: "of Silence" },
    { roll: "91", name: "of Sinking" },
    { roll: "92", name: "of Slaying" },
    { roll: "93", name: "of Slaying II" },
    { roll: "94", name: "of Slaying III" },
    { roll: "95", name: "of Slaying IV" },
    { roll: "96", name: "Snake" },
    { roll: "97", name: "of Speaking" },
    { roll: "98", name: "Stun Bolt" },
    { roll: "99", name: "of Stunning" },
    { roll: "100", name: "Stirge's Bite" },
    { roll: "101", name: "of Teleporting" },
    { roll: "102", name: "of Transporting" },
    { roll: "103", name: "Wooden" },
    { roll: "104", name: "of Wounding" },
    { roll: "105-106", name: "Arrowhead of Marking" },
  ],
  "Axe": [
    { roll: "107", name: "Agni's Red" },
    { roll: "108", name: "Ama-Tsu-Mara's Vorpal" },
    { roll: "109", name: "Arumdina" },
    { roll: "110", name: "Azuredge" },
    { roll: "111", name: "Brihaspati's" },
    { roll: "112", name: "of Brotherhood" },
    { roll: "113", name: "Callarduran Smoothhands" },
    { roll: "114", name: "Cursed Battle" },
    { roll: "115", name: "of Cutting" },
    { roll: "116", name: "Deathstriker" },
    { roll: "117", name: "of the Dwarvish Lords" },
    { roll: "118", name: "of Enchantment" },
    { roll: "119", name: "Frostreaver" },
    { roll: "120", name: "Garl Glittergold's Battle" },
    { roll: "121", name: "Gnarldan's Battle" },
    { roll: "122", name: "Hastseltsi's Hand" },
    { roll: "123-124", name: "Hastsezini's Hand" },
    { roll: "125", name: "of Hurling" },
    { roll: "126", name: "Lortz's Battle" },
    { roll: "127", name: "Maglubiyet's" },
    { roll: "128", name: "Might of Heroes" },
    { roll: "129", name: "Molydeus'" },
    { roll: "130", name: "Motopua" },
    { roll: "131", name: "Nanna Sin's Black" },
    { roll: "132", name: "Nomog-Geaya's Hand" },
    { roll: "133", name: "Pickaxe of Piercing" },
    { roll: "134", name: "Rocksplitter" },
    { roll: "135", name: "Sampsa's Golden" },
    { roll: "136", name: "Shag's Battle" },
    { roll: "137", name: "Sulward's" },
    { roll: "138", name: "Thor's Kiss" },
    { roll: "139", name: "Throwing" },
    { roll: "140", name: "Thumb Height Man's" },
    { roll: "141-142", name: "Torshorak" },
    { roll: "143", name: "Tunnelrunner's" },
    { roll: "144", name: "Withering Pickaxe" },
    { roll: "145", name: "of the Woodsman" },
    { roll: "146", name: "Zebulon's of Leaving" },
    { roll: "147", name: "Zzzzzz's of Snoring" },
  ],
  "Ballista": [
    { roll: "148", name: "Heavy" },
    { roll: "149", name: "Light" },
    { roll: "150", name: "Medium" },
  ],
  "Battering Ram": [
    { roll: "151", name: "Bigby's Demanding" },
    { roll: "152", name: "Magical" },
  ],
  "Blowgun": [
    { roll: "153", name: "of Accuracy" },
    { roll: "154", name: "of Distance" },
    { roll: "155", name: "Hawk" },
    { roll: "156", name: "of Wild Emotions" },
  ],
  "Bow": [
    { roll: "157", name: "Aasimon" },
    { roll: "158-159", name: "of Accuracy" },
    { roll: "160", name: "Ajagava" },
    { roll: "161", name: "of Anshan" },
    { roll: "162", name: "Black" },
    { roll: "163", name: "Brihaspati's" },
    { roll: "164", name: "of the Centaurs" },
    { roll: "165", name: "Corellon's Long" },
    { roll: "166", name: "Crossbow of Accuracy" },
    { roll: "167", name: "Crossbow of Angling" },
    { roll: "168", name: "Crossbow of Distance" },
    { roll: "169", name: "Crossbow of Enchantment" },
    { roll: "170", name: "Crossbow of Klee" },
    { roll: "171", name: "Crossbow of Multiplication" },
    { roll: "172", name: "Crossbow of Speed" },
    { roll: "173", name: "Crossbow of Speed II" },
    { roll: "174", name: "Cursed" },
    { roll: "175", name: "of Distance" },
    { roll: "176-177", name: "of Doubling" },
    { roll: "178", name: "Eagle" },
    { roll: "179", name: "of Enchantment" },
    { roll: "180", name: "Firebow" },
    { roll: "181", name: "Fire Teeth" },
    { roll: "182", name: "of the Forest" },
    { roll: "183", name: "Gem" },
    { roll: "184", name: "Goblins' Bane" },
    { roll: "185", name: "Hastsezini's" },
    { roll: "186", name: "Hawk" },
    { roll: "187", name: "Heartseeker" },
    { roll: "188", name: "of Heartseeking" },
    { roll: "189", name: "of Vampire Slaying" },
    { roll: "190", name: "Heracles'" },
    { roll: "191", name: "Hiatea's Long" },
    { roll: "192", name: "Ice Fang" },
    { roll: "193", name: "Illusory" },
    { roll: "194-195", name: "Indra's" },
    { roll: "196", name: "Iron of Gesen" },
    { roll: "197", name: "Joukahainen's Crossbow" },
    { roll: "198", name: "Last Shot" },
    { roll: "199", name: "of Levitation" },
    { roll: "200", name: "of Lir" },
    { roll: "201", name: "of Marksmanship" },
    { roll: "202", name: "of Neverending Arrows" },
    { roll: "203", name: "Oberon's" },
    { roll: "204", name: "Odin's" },
    { roll: "205", name: "Phantom" },
    { roll: "206", name: "Rudra's" },
    { roll: "207", name: "Sarnge" },
    { roll: "208", name: "Shichi's Daikyu" },
    { roll: "209", name: "Solonor Thelandira's" },
    { roll: "210", name: "of Speed" },
    { roll: "211-212", name: "Underwater Crossbow" },
    { roll: "213", name: "of the Unicorn" },
    { roll: "214", name: "Valis'" },
    { roll: "215", name: "of Vampire Slaying" },
    { roll: "216", name: "of Warning With Curse" },
    { roll: "217", name: "of Warning Without Curse" },
  ],
  "Catapult": [
    { roll: "218", name: "Light" },
    { roll: "219", name: "Medium" },
    { roll: "220", name: "Heavy" },
  ],
  "Club": [
    { roll: "221", name: "Aegir's" },
    { roll: "222", name: "Bronzewood Cudgel" },
    { roll: "223", name: "Daghdha's" },
    { roll: "224", name: "Druid's Cudgel" },
    { roll: "225", name: "Fire's" },
    { roll: "226", name: "Great Stone" },
    { roll: "227", name: "Grolantor's" },
    { roll: "228", name: "Crutch of Lightning" },
  ],
  "Dagger": [
    { roll: "229-230", name: "Abbathor's" },
    { roll: "231", name: "Alignment Detection" },
    { roll: "232", name: "Aphrodite's" },
    { roll: "233", name: "Armor Piercing" },
    { roll: "234", name: "Baravar Cloakshadow's" },
    { roll: "235", name: "of Blackflame" },
    { roll: "236", name: "Blade of Banishing" },
    { roll: "237", name: "Bladestar" },
    { roll: "238", name: "Brandobaris'" },
    { roll: "239", name: "Buckle Knife" },
    { roll: "240", name: "Buckler Knife" },
    { roll: "241", name: "Ceremonial" },
    { roll: "242", name: "Chih-Nii's" },
    { roll: "243", name: "Chill Blade" },
    { roll: "244", name: "of Concealment" },
    { roll: "245", name: "of Defiance" },
    { roll: "246", name: "Dolphins' Bane" },
    { roll: "247-248", name: "of Doomwarding" },
    { roll: "249", name: "Dragon Fang" },
    { roll: "250", name: "Dragonfang" },
    { roll: "251", name: "Elven" },
    { roll: "252", name: "of the Evil Eye" },
    { roll: "253", name: "Eviscerator" },
    { roll: "254", name: "Fang" },
    { roll: "255", name: "Fang of the Nosferatu" },
    { roll: "256", name: "Flying" },
    { roll: "257", name: "Flying II" },
    { roll: "258", name: "Freya's Fiery" },
    { roll: "259", name: "Frigga's" },
    { roll: "260", name: "Golemblight" },
    { roll: "261", name: "Grimwald's" },
    { roll: "262", name: "Guardian Blade" },
    { roll: "263", name: "Hastseltsi's Throwing" },
    { roll: "264-265", name: "Hecate's" },
    { roll: "266", name: "Hornblade (Knife-sized)" },
    { roll: "267", name: "Hornblade (Dagger-sized)" },
    { roll: "268", name: "of Illusory Metal" },
    { roll: "269", name: "of Impaling" },
    { roll: "270", name: "Iyarim's Flying" },
    { roll: "271", name: "Jump" },
    { roll: "272", name: "Kiaransalee's" },
    { roll: "273", name: "Knife of Continual Sharpness*" },
    { roll: "274", name: "Knife of Sharpness" },
    { roll: "275", name: "Koalinth Slayer" },
    { roll: "276", name: "Loki's Envenomed" },
    { roll: "277", name: "Longtooth" },
    { roll: "278", name: "Mageslayer" },
    { roll: "279", name: "of the Magius" },
    { roll: "280", name: "Mervic's" },
    { roll: "281", name: "Nut's Black" },
    { roll: "282-283", name: "of Quickness" },
    { roll: "284", name: "Rabbitslayer" },
    { roll: "285", name: "Random Target" },
    { roll: "286", name: "Resource" },
    { roll: "287", name: "Rust Blade" },
    { roll: "288", name: "Rutterkin Sling Blade" },
    { roll: "289", name: "Sahuagin Dolphin" },
    { roll: "290", name: "of Set" },
    { roll: "291", name: "Soma's" },
    { roll: "292", name: "of Sounding" },
    { roll: "293", name: "Speaking" },
    { roll: "294", name: "Spider Fang" },
    { roll: "295", name: "Sung Chiang's" },
    { roll: "296", name: "of Throwing" },
    { roll: "297", name: "of Throwing II" },
    { roll: "298", name: "Throwing of Returning" },
    { roll: "299", name: "Tooth of Torm" },
    { roll: "300-301", name: "of Truth" },
    { roll: "302", name: "Tufala's Jambiya" },
    { roll: "303", name: "Tvashtri's" },
    { roll: "304", name: "of Vengeance" },
    { roll: "305", name: "of Venom" },
    { roll: "306", name: "Werebane" },
    { roll: "307", name: "Xochiquetzal's" },
    { roll: "308", name: "Yama's" },
  ],
  "Dart": [
    { roll: "309", name: "of Biting" },
    { roll: "310", name: "of Blinking" },
    { roll: "311", name: "of Branding" },
    { roll: "312", name: "of Charming" },
    { roll: "313", name: "of Climbing" },
    { roll: "314", name: "of Curing" },
    { roll: "315", name: "Death" },
    { roll: "316", name: "Death II" },
    { roll: "317-318", name: "of Disarming" },
    { roll: "319", name: "of Dispelling" },
    { roll: "320", name: "of Flying" },
    { roll: "321", name: "of Homing" },
    { roll: "322", name: "of the Hornets' Nest" },
    { roll: "323", name: "Illusory Missiles" },
    { roll: "324", name: "of Light" },
    { roll: "325", name: "of Lighting" },
    { roll: "326", name: "of Penetrating" },
    { roll: "327", name: "of Refilling" },
    { roll: "328", name: "of Screaming" },
    { roll: "329", name: "of Seeking" },
    { roll: "330", name: "of Sinking" },
    { roll: "331", name: "of Slaying" },
    { roll: "332", name: "of Speaking" },
    { roll: "333", name: "of Stunning" },
    { roll: "334", name: "Svirfnebli" },
    { roll: "335-336", name: "of Teleporting" },
    { roll: "337", name: "of Transporting" },
    { roll: "338", name: "of Wounding" },
    { roll: "339", name: "Discus of Disenchantment" },
  ],
  "Explosive Device": [
    { roll: "340", name: "Dimensional Mine" },
    { roll: "341", name: "Dimensional Mine II" },
    { roll: "342", name: "Ellister's Dimensional Mine" },
    { roll: "343", name: "Helm Bomb" },
    { roll: "344", name: "Spelljamming Mine" },
    { roll: "345", name: "Wethilion's Time Bomb" },
  ],
  "Flail Weapon": [
    { roll: "346", name: "Bael's Morning Star" },
    { roll: "347", name: "Bargrivyek's" },
    { roll: "348", name: "Battle Star" },
    { roll: "349", name: "of the Desert Kings" },
    { roll: "350", name: "Dragonflail" },
    { roll: "351", name: "Fleeting" },
    { roll: "352", name: "Morning Star of Detection" },
    { roll: "353-354", name: "Multiple Rod of Dancing" },
    { roll: "355", name: "Osiris' Royal" },
    { roll: "356", name: "Pharaohs" },
    { roll: "357", name: "Gnomish Sweeper" },
  ],
  "Hammer": [
    { roll: "358", name: "Aegis-Fang" },
    { roll: "359", name: "Air" },
    { roll: "360", name: "Golgomere's of Thunderbolts" },
    { roll: "361", name: "Delzoun's Fist" },
    { roll: "362", name: "Dwarf Thrower" },
    { roll: "363", name: "Dwarf Thrower II" },
    { roll: "364", name: "Flandal Steelskin's" },
    { roll: "365", name: "Gaerdal Ironhand's" },
    { roll: "366", name: "Goibhniu's War" },
    { roll: "367", name: "Hephaestus'" },
    { roll: "368", name: "Kostchtchie's" },
    { roll: "369", name: "Kostchtchie's II" },
    { roll: "370-371", name: "of Life" },
    { roll: "372", name: "Mallet of Luck" },
    { roll: "373", name: "Maul of the Titans" },
    { roll: "374", name: "Mjolnir II" },
    { roll: "375", name: "of Nailing" },
    { roll: "376", name: "Nai No Kami's" },
    { roll: "377", name: "of Penetration" },
    { roll: "378", name: "Runehammer" },
    { roll: "379", name: "of Silence" },
    { roll: "380", name: "Storm" },
    { roll: "381", name: "Stronmaus' of Thunderbolts" },
    { roll: "382", name: "of Thunderbolts" },
    { roll: "383", name: "of Vengence" },
    { roll: "384", name: "of Vitroin" },
    { roll: "385", name: "Whelm" },
    { roll: "386", name: "Winged" },
  ],
  "Harpoon": [
    { roll: "387", name: "Magical" },
  ],
  "Helmseeker": [
    { roll: "388-389", name: "Accelerator" },
    { roll: "390", name: "Ballista" },
    { roll: "391", name: "Bombard" },
    { roll: "392", name: "Catapult" },
    { roll: "393", name: "Great Bombard" },
    { roll: "394", name: "Greek Fire" },
    { roll: "395", name: "Jettison Medium" },
  ],
  "Javelin": [
    { roll: "396", name: "Cursed" },
    { roll: "397", name: "of Distance" },
    { roll: "398", name: "Hruggek's of Lightning" },
    { roll: "399", name: "Huitzilopochtli's" },
    { roll: "400", name: "of Lightning" },
    { roll: "401", name: "of Piercing" },
    { roll: "402", name: "Sunbolt" },
  ],
  "Jettison": [
    { roll: "403", name: "Light Magical" },
    { roll: "404", name: "Medium Magical" },
    { roll: "405", name: "Heavy Magical" },
    { roll: "406-407", name: "Light Magical II" },
    { roll: "408", name: "Medium Magical II" },
    { roll: "409", name: "Heavy Magical II" },
  ],
  "Lance": [
    { roll: "410", name: "Anhur's" },
    { roll: "411", name: "Copper" },
    { roll: "412", name: "Death" },
    { roll: "413", name: "Footman Dragonlance" },
    { roll: "414", name: "Mounted Dragonlance" },
    { roll: "415", name: "of Fire" },
    { roll: "416", name: "Hastsezini's Lance of" },
    { roll: "417", name: "Izanagi's" },
    { roll: "418", name: "Lesser Footman's Dragonlance" },
    { roll: "419", name: "Lesser Mounted Dragonlance" },
    { roll: "420", name: "of Piercing" },
    { roll: "421", name: "Puchan's Golden" },
    { roll: "422", name: "Tribal" },
    { roll: "423-424", name: "True Dragonlance" },
    { roll: "425", name: "Venom" },
    { roll: "426", name: "Wind's" },
  ],
  "Mace": [
    { roll: "427", name: "Astral Deva" },
    { roll: "428", name: "Bael's Morning Star" },
    { roll: "429", name: "Berronar Truesilver's" },
    { roll: "430", name: "Black" },
    { roll: "431", name: "of Crushing" },
    { roll: "432", name: "of Darkness" },
    { roll: "433", name: "Diamond" },
    { roll: "434", name: "of Disruption" },
    { roll: "435", name: "Driver" },
    { roll: "436", name: "Expeller" },
    { roll: "437", name: "Great Golden of the North" },
    { roll: "438", name: "Great Holy Icon" },
    { roll: "439", name: "Hruggek's Morning Star" },
    { roll: "440", name: "Ironstar" },
    { roll: "441-442", name: "Mace-Wand" },
    { roll: "443", name: "Memnor's Morning Star" },
    { roll: "444", name: "Muamman Duathal's" },
    { roll: "445", name: "Nebelun's" },
    { roll: "446", name: "Nightbringer" },
    { roll: "447", name: "of Pain" },
    { roll: "448", name: "Raiden's" },
    { roll: "449", name: "Shadowcaster" },
    { roll: "450", name: "Skull" },
    { roll: "451", name: "of Spellwarding" },
    { roll: "452", name: "of St. Cuthbert" },
    { roll: "453", name: "of St. Cuthbert II" },
    { roll: "454", name: "of St. Cuthbert III" },
    { roll: "455", name: "Staff-Mace" },
    { roll: "456", name: "Storm Star" },
    { roll: "457", name: "Tadrond's" },
    { roll: "458", name: "Undeadbane" },
    { roll: "459-460", name: "Undeadbane II" },
    { roll: "461", name: "Varuna's" },
    { roll: "462", name: "Warstar of the Manticore" },
  ],
  "Mattock": [
    { roll: "463", name: "Dumathoin's" },
    { roll: "464", name: "of the Titans" },
  ],
  "Net": [
    { roll: "465", name: "Ashley's of Entrapment" },
    { roll: "466", name: "Drag" },
    { roll: "467", name: "of Entrapment" },
    { roll: "468", name: "of Fishing" },
    { roll: "469", name: "Hare" },
    { roll: "470", name: "Hiatea's of Weakness" },
    { roll: "471", name: "Hiatea's of Feeblemind" },
    { roll: "472", name: "Hiatea's of Petrification" },
    { roll: "473", name: "of Landing" },
    { roll: "474", name: "Loyal of Restraint" },
    { roll: "475", name: "of Plenty" },
    { roll: "476-477", name: "of Profit" },
    { roll: "478", name: "Safety" },
    { roll: "479", name: "of Snaring" },
    { roll: "480", name: "of Snaring II" },
    { roll: "481", name: "of Sneering" },
    { roll: "482", name: "of Spirit Snaring" },
    { roll: "483", name: "Webnet" },
    { roll: "484", name: "Webnet II" },
    { roll: "485", name: "of Worth" },
    { roll: "486", name: "Noisesome Spirit Chasers" },
  ],
  "Paddleboard": [
    { roll: "487", name: "Magical" },
    { roll: "488", name: "of Wondrous Transformation" },
  ],
  "Pellet": [
    { roll: "489", name: "Flash" },
    { roll: "490", name: "Flash II" },
  ],
  "Polearm": [
    { roll: "491", name: "Baphome's Bardiche" },
    { roll: "492", name: "Belial's Military Fork" },
    { roll: "493", name: "Blessed Trident" },
    { roll: "494-495", name: "of Commanding Water Creatures" },
    { roll: "496", name: "Fisher's Trident of Fish Command" },
    { roll: "497", name: "Fork of Jabbing" },
    { roll: "498", name: "Fork of Travel" },
    { roll: "499", name: "Lacedonbane" },
    { roll: "500", name: "Mephistopheles' Fork" },
    { roll: "501", name: "Niord's Great Trident" },
    { roll: "502", name: "O-Wata-Tsu-Mi's Jade Trident" },
    { roll: "503", name: "Persana's Trident" },
    { roll: "504", name: "Pitchfork of Penetration" },
    { roll: "505", name: "Poseidon's Trident" },
    { roll: "506", name: "Reptilebane" },
    { roll: "507", name: "Rutterkin Polearm" },
    { roll: "508", name: "Saw-Toothed Glaive" },
    { roll: "509", name: "Trident of Elemental Death" },
    { roll: "510", name: "Trident of Fish Command" },
    { roll: "511", name: "Trident of Fish Control" },
    { roll: "512-513", name: "Trident/Military Fork" },
    { roll: "514", name: "Trident of the Oljatt Sea" },
    { roll: "515", name: "Trident of the Phlogiston" },
    { roll: "516", name: "Trident of Submission" },
    { roll: "517", name: "Trident of Warning" },
    { roll: "518", name: "Trident of Yearning" },
    { roll: "519", name: "Uluth'gak's Gythka" },
    { roll: "520", name: "Water Elemental Slayer" },
    { roll: "521", name: "Wave" },
    { roll: "522", name: "Zezen Washio's Trident" },
  ],
  "Quiver": [
    { roll: "523", name: "of Arrow Storing" },
    { roll: "524", name: "Black" },
    { roll: "525", name: "of Ehlonna" },
    { roll: "526", name: "Frief's Magical" },
    { roll: "527", name: "Never Empty" },
    { roll: "528", name: "of Returning" },
    { roll: "529-530", name: "of Wrong Returning" },
    { roll: "531", name: "Rutterkin Snap-Tong" },
  ],
  "Shot": [
    { roll: "532", name: "Mage Shot (Dust)" },
    { roll: "533", name: "Mage Shot (Ring)" },
    { roll: "534", name: "Mage Shot (Snow)" },
    { roll: "535", name: "Mage Shot II (Shatter)" },
    { roll: "536", name: "Mage Shot II (Skunk)" },
    { roll: "537", name: "Mage Shot II (Termite)" },
    { roll: "538", name: "Mage Shot III (Warp)" },
    { roll: "539", name: "Mage Shot III (Shrapnel)" },
  ],
  "Sickle": [
    { roll: "540", name: "Ahto's" },
    { roll: "541", name: "Black" },
    { roll: "542", name: "Cronus'" },
    { roll: "543", name: "Gaea's Black" },
    { roll: "544", name: "Golden" },
    { roll: "545", name: "of the Harvest" },
    { roll: "546", name: "of Lycanthropy" },
    { roll: "547-548", name: "Scythe of Pain" },
  ],
  "Sling": [
    { roll: "549", name: "Blacksling" },
    { roll: "550", name: "Bolas of Sunlight" },
    { roll: "551", name: "Finniginn's" },
    { roll: "552", name: "of Seeking" },
    { roll: "553", name: "Sling Bullet of Impact" },
    { roll: "554", name: "Sling Stone of Pulverizing" },
  ],
  "Spear": [
    { roll: "555", name: "of Accuracy" },
    { roll: "556", name: "Ares'" },
    { roll: "557", name: "Athena's" },
    { roll: "558", name: "Backbiter" },
    { roll: "559", name: "Black Kumade" },
    { roll: "560", name: "Demeter's" },
    { roll: "561", name: "Gae Bolg" },
    { roll: "562", name: "Goibhniu's" },
    { roll: "563", name: "Gruumsh's" },
    { roll: "564", name: "Gungnir" },
    { roll: "565-566", name: "Gungnir II" },
    { roll: "567", name: "Hadrion's" },
    { roll: "568", name: "Heartseeker" },
    { roll: "569", name: "Heartseeker II" },
    { roll: "570", name: "Heartwood" },
    { roll: "571", name: "Hiatea's" },
    { roll: "572", name: "of Obliteration" },
    { roll: "573", name: "of Panic" },
    { roll: "574", name: "of Paralysis" },
    { roll: "575", name: "Returning" },
    { roll: "576", name: "Sharksbane" },
    { roll: "577", name: "Smokespear" },
    { roll: "578", name: "Sparkling" },
    { roll: "579", name: "of Vix" },
    { roll: "580", name: "of Yang" },
    { roll: "581", name: "Zeus'" },
  ],
  "Spelljamming Ram": [
    { roll: "582-583", name: "Blunt" },
    { roll: "584", name: "Grappling" },
    { roll: "585", name: "Piercing" },
  ],
  "Sword": [
    { roll: "586", name: "Aasimon" },
    { roll: "587", name: "of Abhorrence of Shape Changers" },
    { roll: "588", name: "Adjatha the Drinker" },
    { roll: "589", name: "Albruin" },
    { roll: "590", name: "Amatsu-Mikaboshi's" },
    { roll: "591", name: "Anduvar" },
    { roll: "592", name: "Angurvadal" },
    { roll: "593", name: "Annacon" },
    { roll: "594", name: "Ansanther" },
    { roll: "595", name: "Answerer" },
    { roll: "596", name: "Answerer II (Rebutter)" },
    { roll: "597", name: "Answerer III (Scather)" },
    { roll: "598", name: "Answerer IV (Replier)" },
    { roll: "599", name: "Answerer V (Retorter)" },
    { roll: "600-601", name: "Answerer VI (Squelcher)" },
    { roll: "602", name: "Answerer VII (Backtalker)" },
    { roll: "603", name: "Anton's Vorpal Blade" },
    { roll: "604", name: "of Arak" },
    { roll: "605", name: "Arbane's of Agility" },
    { roll: "606", name: "Ar'ondight" },
    { roll: "607", name: "Arvoreen's" },
    { roll: "608", name: "of Arvoreen" },
    { roll: "609", name: "of Assassination" },
    { roll: "610", name: "Aziza's Scimitar of Dancing" },
    { roll: "611", name: "of Azor'alq" },
    { roll: "612", name: "of Backstabbing" },
    { roll: "613", name: "Balisarda" },
    { roll: "614", name: "Balmung" },
    { roll: "615", name: "Balor" },
    { roll: "616", name: "Bamboo Scimitar" },
    { roll: "617", name: "Bane of Enchanted Beings" },
    { roll: "618-619", name: "Bane of the North" },
    { roll: "620", name: "Barnus' Gnomebane" },
    { roll: "621", name: "of Bast" },
    { roll: "622", name: "Belenus'" },
    { roll: "623", name: "of the Believer" },
    { roll: "624", name: "Benn Griff's" },
    { roll: "625", name: "Berserk Dancing" },
    { roll: "626", name: "Black" },
    { roll: "627", name: "Black Flame" },
    { roll: "628", name: "Blackflame" },
    { roll: "629", name: "of Blackflame" },
    { roll: "630", name: "Blackjammer's Cutlass" },
    { roll: "631", name: "Blackrazor" },
    { roll: "632", name: "Blade of Black Ice" },
    { roll: "633", name: "Blade of Corusk" },
    { roll: "634", name: "Blade of Lathander" },
    { roll: "635-636", name: "Bladeless" },
    { roll: "637", name: "Blood Drinker" },
    { roll: "638", name: "Bloodletter" },
    { roll: "639", name: "Bloodsword" },
    { roll: "640", name: "Blue Dragon Bane" },
    { roll: "641", name: "Brightblade" },
    { roll: "642", name: "Caeren-Uroth" },
    { roll: "643", name: "Calathangas" },
    { roll: "644", name: "Canopa's" },
    { roll: "645", name: "Captain's" },
    { roll: "646", name: "Casterbane" },
    { roll: "647", name: "Celestial Fury" },
    { roll: "648", name: "Chainsword" },
    { roll: "649", name: "of Charm Person" },
    { roll: "650", name: "Chopping" },
    { roll: "651", name: "Clamorour" },
    { roll: "652", name: "of Cleaving" },
    { roll: "653-654", name: "Colada" },
    { roll: "655", name: "of Cold" },
    { roll: "656", name: "Companion" },
    { roll: "657", name: "Corellon's" },
    { roll: "658", name: "Corthalis" },
    { roll: "659", name: "Courtain" },
    { roll: "660", name: "of Cowardice" },
    { roll: "661", name: "Crusader" },
    { roll: "662", name: "Crysomer" },
    { roll: "663", name: "Cuprumbane" },
    { roll: "664", name: "Cursed" },
    { roll: "665", name: "Cursed II" },
    { roll: "666", name: "Cursed Berserker" },
    { roll: "667", name: "Cutter" },
    { roll: "668", name: "of Cymrych Hugh" },
    { roll: "669", name: "Cyric's" },
    { roll: "670", name: "Dale" },
    { roll: "671-672", name: "of Dancing" },
    { roll: "673", name: "Dancing of Bronze" },
    { roll: "674", name: "Dancing of Lightning" },
    { roll: "675", name: "Darius'" },
    { roll: "676", name: "Death-to-Monsters" },
    { roll: "677", name: "Deep Sashelas'" },
    { roll: "678", name: "Defender" },
    { roll: "679", name: "Desert Blade" },
    { roll: "680", name: "Dragonbait's Holy Avenger" },
    { roll: "681", name: "Dragon Claw" },
    { roll: "682", name: "Dragon Crippler" },
    { roll: "683", name: "Dragon Slayer" },
    { roll: "684", name: "Dragonslayer II" },
    { roll: "685", name: "of Dragon Slaying" },
    { roll: "686", name: "Drain Life Energy" },
    { roll: "687", name: "Draxalon, Defender of Feminine Virtue" },
    { roll: "688-689", name: "Dreamsinger" },
    { roll: "690", name: "Dugmaren Brightmantle's Broad Sword" },
    { roll: "691", name: "Durandan" },
    { roll: "692", name: "Dyerwaen" },
    { roll: "693", name: "of the Ebon Flame" },
    { roll: "694", name: "Ebonbane" },
    { roll: "695", name: "The Edge" },
    { roll: "696", name: "of Efreeti Slaying" },
    { roll: "697", name: "Elkhorn's" },
    { roll: "698", name: "Elquillar" },
    { roll: "699", name: "Elven" },
    { roll: "700", name: "Elven II" },
    { roll: "701", name: "Emperor's" },
    { roll: "702", name: "Enchanted of Sylaire" },
    { roll: "703", name: "Equalizer of Gran March" },
    { roll: "704", name: "Everstriking" },
    { roll: "705", name: "Evil Wyrmslayer" },
    { roll: "706-707", name: "Evithyan's Blade" },
    { roll: "708", name: "Excalibur" },
    { roll: "709", name: "Excalibur II" },
    { roll: "710", name: "Excalibur III" },
    { roll: "711", name: "Farrinae" },
    { roll: "712", name: "Fate's Promise" },
    { roll: "713", name: "Fiendbane" },
    { roll: "714", name: "Final Word (Answerer)" },
    { roll: "715", name: "Final Word (Back-talker)" },
    { roll: "716", name: "Final Word (Concluder)" },
    { roll: "717", name: "Final Word (Lastquip)" },
    { roll: "718", name: "Final Word (Rebutter)" },
    { roll: "719", name: "Final Word (Replier)" },
    { roll: "720", name: "Final Word (Retorter)" },
    { roll: "721", name: "Final Word (Scather)" },
    { roll: "722", name: "Final Word (Squelcher)" },
    { roll: "723", name: "Finder" },
    { roll: "724-725", name: "Fionnghuala's" },
    { roll: "726", name: "Fist of Odin" },
    { roll: "727", name: "Flamberge" },
    { roll: "728", name: "Flame Blade" },
    { roll: "729", name: "Flame of the North" },
    { roll: "730", name: "Flame Tongue" },
    { roll: "731", name: "Flames on Command" },
    { roll: "732", name: "Flaming" },
    { roll: "733", name: "Flaming II" },
    { roll: "734", name: "Floating Blade of Shin Lu" },
    { roll: "735", name: "Flying Scimitar of Tusmit" },
    { roll: "736", name: "Foebane" },
    { roll: "737", name: "Foefinder" },
    { roll: "738", name: "Forseti's" },
    { roll: "739", name: "Frey's" },
    { roll: "740", name: "Frey's II" },
    { roll: "741-742", name: "Frey's Two-Handed" },
    { roll: "743", name: "Frey's Two-Handed II" },
    { roll: "744", name: "Freya's Frost Brand" },
    { roll: "745", name: "of Friendship" },
    { roll: "746", name: "Frost Brand" },
    { roll: "747", name: "Galanti" },
    { roll: "748", name: "Gemsword" },
    { roll: "749", name: "Genie Slayer" },
    { roll: "750", name: "Genies' Bane" },
    { roll: "751", name: "Genies' Bane (Dao) II" },
    { roll: "752", name: "Genies' Bane (Djinn) II" },
    { roll: "753", name: "Genies' Bane (Efreet) II" },
    { roll: "754", name: "Genies' Bane (Marid) II" },
    { roll: "755", name: "Genieblight" },
    { roll: "756", name: "Geniescourge" },
    { roll: "757", name: "Giant Slayer" },
    { roll: "758", name: "of Giant Slaying" },
    { roll: "759-760", name: "of the Giants" },
    { roll: "761", name: "Githyanki Knight's Silver" },
    { roll: "762", name: "Githyanki Leader's Silver" },
    { roll: "763", name: "Glorius" },
    { roll: "764", name: "Goblinvolent" },
    { roll: "765", name: "of the Golden Gulf" },
    { roll: "766", name: "Golembane" },
    { roll: "767", name: "Gram" },
    { roll: "768", name: "Grankhul's" },
    { roll: "769", name: "Graz'zt's" },
    { roll: "770", name: "Greenswathe" },
    { roll: "771", name: "Gregory's Holy Avenger" },
    { roll: "772", name: "Grinthane" },
    { roll: "773", name: "Guardian Blade" },
    { roll: "774", name: "Hachiman's" },
    { roll: "775", name: "Hades'" },
    { roll: "776", name: "Harmonizer" },
    { roll: "777-778", name: "Harpo's Orcslayer" },
    { roll: "779", name: "Hawksblade" },
    { roll: "780", name: "Heart of Stone" },
    { roll: "781", name: "Heartseeker" },
    { roll: "782", name: "Heimdall's" },
    { roll: "783", name: "Hel's" },
    { roll: "784", name: "Ho Masubi's" },
    { roll: "785", name: "Hofud" },
    { roll: "786", name: "Holy" },
    { roll: "787", name: "Holy Avenger" },
    { roll: "788", name: "Holy Revenger" },
    { roll: "789", name: "of Honor" },
    { roll: "790", name: "Hornblade" },
    { roll: "791", name: "of Horus" },
    { roll: "792", name: "Ice Claw" },
    { roll: "793", name: "Ilbratha (Mistress of Battle)" },
    { roll: "794-795", name: "Ilneval's Broadsword" },
    { roll: "796", name: "Ilyana" },
    { roll: "797", name: "Indra's Flaming" },
    { roll: "798", name: "of Insanity" },
    { roll: "799", name: "of Intercession" },
    { roll: "800", name: "Ironfang" },
    { roll: "801", name: "Jaysen's Magebane" },
    { roll: "802", name: "Joyeuse" },
    { roll: "803", name: "Justicer" },
    { roll: "804", name: "Kabal" },
    { roll: "805", name: "Kaldair Swiftfoot's" },
    { roll: "806", name: "Kali's" },
    { roll: "807", name: "Karali's Silver" },
    { roll: "808", name: "Kirren's Frostbrand" },
    { roll: "809", name: "Kullervo's" },
    { roll: "810", name: "Kura (The Darkness)" },
    { roll: "811", name: "Kusunogi no Tsurugi (Grass Quelling)" },
    { roll: "812-813", name: "Lafarallinn's" },
    { roll: "814", name: "Lancelin's" },
    { roll: "815", name: "Laprov" },
    { roll: "816", name: "Lassiviren's" },
    { roll: "817", name: "Lemmikainen's" },
    { roll: "818", name: "Life Saver" },
    { roll: "819", name: "Life Stealing" },
    { roll: "820", name: "Life Taker" },
    { roll: "821", name: "of Light" },
    { roll: "822", name: "Lightning Blade" },
    { roll: "823", name: "Locate Object" },
    { roll: "824", name: "Elven of Luck" },
    { roll: "825", name: "Luck Blade" },
    { roll: "826", name: "Lydia's Broadsword" },
    { roll: "827", name: "of Lyons" },
    { roll: "828", name: "Malign" },
    { roll: "829", name: "Madoc's" },
    { roll: "830-831", name: "Mamluk of Obedience" },
    { roll: "832", name: "of Mammal Slaying" },
    { roll: "833", name: "Mantooth" },
    { roll: "834", name: "Mantooth II" },
    { roll: "835", name: "Maroon" },
    { roll: "836", name: "Mayonaka's Silver Katana" },
    { roll: "837", name: "Melior" },
    { roll: "838", name: "Meredin's Luck Blade" },
    { roll: "839", name: "Mimung" },
    { roll: "840", name: "Mitra's of Light" },
    { roll: "841", name: "Monster Slayer" },
    { roll: "842", name: "Moon Blade" },
    { roll: "843", name: "Morglay" },
    { roll: "844", name: "Movanic Deva" },
    { roll: "845", name: "Naesowen (Ghost Blade)" },
    { roll: "846", name: "Nagelring" },
    { roll: "847-848", name: "Namara Neversleep" },
    { roll: "849", name: "Neekar" },
    { roll: "850", name: "Nepanth" },
    { roll: "851", name: "of Night" },
    { roll: "852", name: "Nightwatcher" },
    { roll: "853", name: "Nightwind" },
    { roll: "854", name: "Nine Lives Stealer" },
    { roll: "855", name: "Nine Steps Draining" },
    { roll: "856", name: "Nomog-Geaya's Broadsword" },
    { roll: "857", name: "Oberon's" },
    { roll: "858", name: "of Odin" },
    { roll: "859", name: "Odin's" },
    { roll: "860", name: "of Olynthos" },
    { roll: "861", name: "Owen's" },
    { roll: "862", name: "Paramel" },
    { roll: "863", name: "Partisan" },
    { roll: "864", name: "Peacemaker" },
    { roll: "865-866", name: "Peregrin's" },
    { roll: "867", name: "Phantom" },
    { roll: "868", name: "Philippan" },
    { roll: "869", name: "Piercer" },
    { roll: "870", name: "Plak's" },
    { roll: "871", name: "of the Planes" },
    { roll: "872", name: "Poisonsword" },
    { roll: "873", name: "Porpherio's" },
    { roll: "874", name: "Purta Blue's" },
    { roll: "875", name: "of Quickness" },
    { roll: "876", name: "Ratri's" },
    { roll: "877", name: "Red Death" },
    { roll: "878", name: "Red Robin" },
    { roll: "879", name: "Red Sabre" },
    { roll: "880", name: "Redeemer" },
    { roll: "881", name: "Rel Astran" },
    { roll: "882", name: "Ren's of Dancing" },
    { roll: "883-884", name: "Reptilian Legionnaire" },
    { roll: "885", name: "Retaliator" },
    { roll: "886", name: "Retaliator II" },
    { roll: "887", name: "Rutterkin Flatchet" },
    { roll: "888", name: "of the Sands" },
    { roll: "889", name: "Sauvagine" },
    { roll: "890", name: "Savitri's" },
    { roll: "891", name: "Scale Cleaver" },
    { roll: "892", name: "Scales of Justice" },
    { roll: "893", name: "Scalebane" },
    { roll: "894", name: "Schakha" },
    { roll: "895", name: "Scimitar of Speed" },
    { roll: "896", name: "Scorbane" },
    { roll: "897", name: "Scourge of Regenerators" },
    { roll: "898", name: "Serpent Slicer" },
    { roll: "899", name: "Sess'innek's Two-Handed" },
    { roll: "900-901", name: "Sess'innek's One-Handed" },
    { roll: "902", name: "Seventh Blade" },
    { roll: "903", name: "Shadowsword" },
    { roll: "904", name: "Shalandain's Holy Avenger" },
    { roll: "905", name: "of Shame" },
    { roll: "906", name: "Sun Blade, Sh'arien" },
    { roll: "907", name: "of Sharpness" },
    { roll: "908", name: "Shazzellim" },
    { roll: "909", name: "Shichi's Katana" },
    { roll: "910", name: "Shimmering Blade of Shin Ginsen" },
    { roll: "911", name: "Shina-Tsu-Hiko's" },
    { roll: "912", name: "Shock Blade" },
    { roll: "913", name: "Shu's" },
    { roll: "914", name: "Sif's" },
    { roll: "915", name: "Singing" },
    { roll: "916", name: "Siva's Scimitar" },
    { roll: "917", name: "of Skewering" },
    { roll: "918-919", name: "Slayer" },
    { roll: "920", name: "Snakebane" },
    { roll: "921", name: "Snoop" },
    { roll: "922", name: "Snow on the Mountain" },
    { roll: "923", name: "Soulblade" },
    { roll: "924", name: "of Souls" },
    { roll: "925", name: "Soulseeker" },
    { roll: "926", name: "Special" },
    { roll: "927", name: "Spectral" },
    { roll: "928", name: "Spellbinder" },
    { roll: "929", name: "Spellblade" },
    { roll: "930", name: "Stalker" },
    { roll: "931", name: "Starfall" },
    { roll: "932", name: "Stonefist" },
    { roll: "933", name: "Stormbringer" },
    { roll: "934", name: "Sun Blade" },
    { roll: "935", name: "Sunsword" },
    { roll: "936-937", name: "Surtr's Flaming" },
    { roll: "938", name: "Surya's of Light" },
    { roll: "939", name: "Susanoo's Blue" },
    { roll: "940", name: "Susk" },
    { roll: "941", name: "Sylabra" },
    { roll: "942", name: "Syrar's Silver" },
    { roll: "943", name: "Taragarth" },
    { roll: "944", name: "Tarl Vanovitch's Sun Blade" },
    { roll: "945", name: "Tefnut's" },
    { roll: "946", name: "Tideripper" },
    { roll: "947", name: "Timesweep" },
    { roll: "948", name: "Token" },
    { roll: "949", name: "Tri-Entity" },
    { roll: "950", name: "Troll's Bane" },
    { roll: "951", name: "Twinkle" },
    { roll: "952", name: "Tyr's of Sharpness" },
    { roll: "953-954", name: "Undead Slayer" },
    { roll: "955", name: "Uranus'" },
    { roll: "956", name: "Vainamoinen's" },
    { roll: "957", name: "Vainamoinen's II" },
    { roll: "958", name: "Vampiric Regeneration" },
    { roll: "959", name: "Vanya's Wrath" },
    { roll: "960", name: "Vasgo" },
    { roll: "961", name: "Vergadain's Broadsword" },
    { roll: "962", name: "Vhaeraun's" },
    { roll: "963", name: "Vorpal" },
    { roll: "964", name: "Vorpal II" },
    { roll: "965", name: "Warbringer" },
    { roll: "966", name: "Warlord Blade of the Shield Lands" },
    { roll: "967", name: "Weasel" },
    { roll: "968", name: "Whirlwind Blade" },
    { roll: "969", name: "White" },
    { roll: "970", name: "of the Wild Coast" },
    { roll: "971-972", name: "Willow Wand" },
    { roll: "973", name: "of Wishes" },
    { roll: "974", name: "Woodhold" },
    { roll: "975", name: "of Wounding" },
    { roll: "976", name: "Wyrmcleaver" },
    { roll: "977", name: "Wyrmsbane" },
    { roll: "978", name: "Wyrmsbane II" },
    { roll: "979", name: "Wyrmslayer" },
    { roll: "980", name: "Wyrmsvenin" },
    { roll: "981", name: "Xiphoid Xebec" },
    { roll: "982", name: "Yondalla's" },
    { roll: "983", name: "Zenchoo Katana" },
    { roll: "984", name: "Zinzerena's" },
  ],
  "Throwing Star (Shuriken)": [
    { roll: "985", name: "of Ojy-do" },
    { roll: "986", name: "of Returning" },
  ],
  "Whip": [
    { roll: "987", name: "of Amatar" },
    { roll: "988", name: "Balor" },
    { roll: "989-990", name: "of Feathers" },
    { roll: "991", name: "of Frost Fire and Fear" },
    { roll: "992", name: "Furies' (Alecto's)" },
    { roll: "993", name: "Furies' (Megarea's)" },
    { roll: "994", name: "Furies' (Tisiphone's)" },
    { roll: "995", name: "Khurgorbaeyag's" },
    { roll: "996", name: "Moloch's" },
    { roll: "997", name: "Purpose" },
    { roll: "998", name: "of Summoning" },
    { roll: "999", name: "Tar's Chaotic Creature" },
    { roll: "0", name: "of Zeif" },
  ],
};

export const S3_CATEGORIES = [
  { name: "✦ Enchanted Enhancements*", min: 1, max: 1, key: "__special__", special: true },
  { name: "✦ Weapon Enhancements*", min: 2, max: 2, key: "__special__", special: true },
  { name: "Accelerator", min: 3, max: 3, key: "__special__", special: true },
  { name: "Arrow", min: 4, max: 106, key: "Arrow", count: 97 },
  { name: "Axe", min: 107, max: 147, key: "Axe", count: 39 },
  { name: "Ballista", min: 148, max: 150, key: "Ballista", count: 3 },
  { name: "Battering Ram", min: 151, max: 152, key: "Battering Ram", count: 2 },
  { name: "Blowgun", min: 153, max: 156, key: "Blowgun", count: 4 },
  { name: "Bow", min: 157, max: 217, key: "Bow", count: 57 },
  { name: "Catapult", min: 218, max: 220, key: "Catapult", count: 3 },
  { name: "Club", min: 221, max: 228, key: "Club", count: 8 },
  { name: "Dagger", min: 229, max: 308, key: "Dagger", count: 75 },
  { name: "Dart", min: 309, max: 339, key: "Dart", count: 29 },
  { name: "Explosive Device", min: 340, max: 345, key: "Explosive Device", count: 6 },
  { name: "Flail Weapon", min: 346, max: 357, key: "Flail Weapon", count: 11 },
  { name: "Hammer", min: 358, max: 386, key: "Hammer", count: 28 },
  { name: "Harpoon", min: 387, max: 387, key: "Harpoon", count: 1 },
  { name: "Helmseeker", min: 388, max: 395, key: "Helmseeker", count: 7 },
  { name: "Javelin", min: 396, max: 402, key: "Javelin", count: 7 },
  { name: "Jettison", min: 403, max: 409, key: "Jettison", count: 6 },
  { name: "Lance", min: 410, max: 426, key: "Lance", count: 16 },
  { name: "Mace", min: 427, max: 462, key: "Mace", count: 34 },
  { name: "Mattock", min: 463, max: 464, key: "Mattock", count: 2 },
  { name: "Net", min: 465, max: 486, key: "Net", count: 21 },
  { name: "Paddleboard", min: 487, max: 488, key: "Paddleboard", count: 2 },
  { name: "Pellet", min: 489, max: 490, key: "Pellet", count: 2 },
  { name: "Polearm", min: 491, max: 522, key: "Polearm", count: 30 },
  { name: "Quiver", min: 523, max: 531, key: "Quiver", count: 8 },
  { name: "Shot", min: 532, max: 539, key: "Shot", count: 8 },
  { name: "Sickle", min: 540, max: 548, key: "Sickle", count: 8 },
  { name: "Sling", min: 549, max: 554, key: "Sling", count: 6 },
  { name: "Spear", min: 555, max: 581, key: "Spear", count: 26 },
  { name: "Spelljamming Ram", min: 582, max: 585, key: "Spelljamming Ram", count: 3 },
  { name: "Sword", min: 586, max: 984, key: "Sword", count: 377 },
  { name: "Throwing Star (Shuriken)", min: 985, max: 986, key: "Throwing Star (Shuriken)", count: 2 },
  { name: "Whip", min: 0, max: 999, key: "Whip", count: 13 },
];
